/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailzy;

import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import mailzy.storage.SQLiteConnector;
import net.atlanticbb.tantlinger.shef.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.GridLayout;
import java.awt.Font;

/**
 *
 * @author hrist
 */
public class MainForm extends javax.swing.JFrame {

	/**
	 * Creates new form MainForm
	 */
	public MainForm() {
		initComponents();

		this.setVisible(true);
		this.connection = null;
		this.mailListDetails = new ArrayList<String[]>();
		this.mailList.setModel(new DefaultListModel<String>());
		try {
			this.connection = new SQLiteConnector();
		} catch (SQLException e) {
			System.out.println(e.getMessage());
			JOptionPane.showMessageDialog(this, "A Database connection error occured!");
			System.exit(1);
		}

		String senderMail = "l.alexandrov@ue-varna.bg";
		// TODO: Fetch credentials from file

		try {
			this.connection.query("SELECT * FROM mails WHERE sender = '" + senderMail + "'");
			ResultSet rs = this.connection.fetch();
			while (rs.next()) {
				String[] row = new String[] { rs.getString("sender"), rs.getString("reciever"),
						rs.getString("recieved_at"), rs.getString("subject"), rs.getString("mail") };
				this.mailListDetails.add(row);
				((DefaultListModel<String>) this.mailList.getModel()).addElement(row[3]);
			}
		} catch (SQLException e) {
			System.out.println(e.getMessage());
			JOptionPane.showMessageDialog(this, "A Database query error occured!");
			System.exit(1);
		}
		// TODO: Fetch data from SMTP, show in application and insert in db (cache)

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		detailsPanel = new javax.swing.JPanel();
		fromLabel = new javax.swing.JLabel();
		toLabel = new javax.swing.JLabel();
		subjectLabel = new javax.swing.JLabel();
		mailTextPane = new javax.swing.JScrollPane();
		mailText = new javax.swing.JEditorPane();
		toInput = new javax.swing.JTextField();
		fromInput = new javax.swing.JTextField();
		subjectInput = new javax.swing.JTextField();
		speechPanel = new javax.swing.JPanel();
		newMailBtn = new javax.swing.JButton();
		newMailBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

			}
		});

		speechBtn = new javax.swing.JToggleButton();
		mainMenuBar = new javax.swing.JMenuBar();
		mailMenu = new javax.swing.JMenu();
		newMailItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		fromLabel.setText("From:");

		toLabel.setText("To:");

		subjectLabel.setText("Subject:");

		mailText.setContentType("text/html");
		mailText.setEditorKit(null);
		mailTextPane.setViewportView(mailText);
		mailText.getAccessibleContext().setAccessibleDescription("");

		javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
		detailsPanelLayout.setHorizontalGroup(detailsPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(detailsPanelLayout.createSequentialGroup().addGroup(detailsPanelLayout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(detailsPanelLayout.createSequentialGroup()
								.addGroup(detailsPanelLayout.createParallelGroup(Alignment.LEADING)
										.addComponent(subjectLabel).addComponent(toLabel, Alignment.TRAILING)
										.addComponent(fromLabel, Alignment.TRAILING))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(detailsPanelLayout.createParallelGroup(Alignment.LEADING)
										.addComponent(toInput, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
										.addComponent(fromInput, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
										.addComponent(subjectInput, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
						.addComponent(mailTextPane, GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
						.addContainerGap()));
		detailsPanelLayout
				.setVerticalGroup(
						detailsPanelLayout.createParallelGroup(Alignment.TRAILING)
								.addGroup(detailsPanelLayout.createSequentialGroup().addGap(1)
										.addGroup(detailsPanelLayout.createParallelGroup(Alignment.BASELINE)
												.addComponent(fromInput, GroupLayout.PREFERRED_SIZE, 31,
														Short.MAX_VALUE)
												.addComponent(fromLabel))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(detailsPanelLayout.createParallelGroup(Alignment.BASELINE)
												.addComponent(toLabel).addComponent(toInput, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(detailsPanelLayout.createParallelGroup(Alignment.BASELINE)
												.addComponent(subjectInput, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(subjectLabel))
										.addGap(18)
										.addComponent(mailTextPane, GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)));
		detailsPanel.setLayout(detailsPanelLayout);

		newMailBtn.setText("New mail");

		javax.swing.GroupLayout speechPanelLayout = new javax.swing.GroupLayout(speechPanel);
		speechPanelLayout.setHorizontalGroup(speechPanelLayout.createParallelGroup(Alignment.TRAILING)
				.addComponent(newMailBtn, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE));
		speechPanelLayout.setVerticalGroup(speechPanelLayout.createParallelGroup(Alignment.TRAILING)
				.addComponent(newMailBtn, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE));
		speechPanel.setLayout(speechPanelLayout);

		speechBtn.setText("Speech");

		mailMenu.setText("New Mail");
		mailMenu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mailMenuActionPerformed(evt);
			}
		});

		newMailItem.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
		newMailItem.setText("New");
		newMailItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newMailItemActionPerformed(evt);
			}
		});
		mailMenu.add(newMailItem);

		mainMenuBar.add(mailMenu);

		setJMenuBar(mainMenuBar);

		mailList = new JList();

		JPanel jPanelMenu = new JPanel();
		jPanelMenu.setBackground(new java.awt.Color(29, 44, 99));
		

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(speechPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(speechBtn))
						.addGroup(layout.createSequentialGroup()
							.addComponent(jPanelMenu, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(mailList, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(detailsPanel, GroupLayout.PREFERRED_SIZE, 466, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(mailList, GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
						.addComponent(detailsPanel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
						.addComponent(jPanelMenu, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(speechPanel, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(speechBtn, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)))
		);

		JLabel lblMenu = new JLabel("");
		lblMenu.setToolTipText("Menu");
		lblMenu.setIcon(new ImageIcon(MainForm.class.getResource("/swing/images/icons8_menu_35px_3.png")));
		lblMenu.setHorizontalAlignment(SwingConstants.CENTER);

		lblMenu.addMouseListener(new MouseAdapter() {
			boolean sideBarOpen = false;

			@Override
			public void mouseClicked(MouseEvent e) {

				if (sideBarOpen == false) {

					// System.out.println( jPanelMenu.getLocationOnScreen().getY() -
					// getContentPane().getLocationOnScreen().getY());
					// System.out.println(jPanelMenu.getSize().height);

					// jPanelMenu.setSize(jPanelMenu.getSize().w,jPanelMenu.getSize().height);
					Thread th = new Thread() {
						@Override
						public void run() {
							for (int i = 45; i <= 150; i++) {
								try {
									Thread.sleep(2);
								} catch (InterruptedException ex) {

								}
								jPanelMenu.setSize(i, jPanelMenu.getSize().height);
								lblMenu.setLocation(i - 37, 10);
							}
							// System.out.println(lblMenu.getLocation());

						}

					};
					th.start();

					sideBarOpen = true;
				}

				else if (sideBarOpen == true) {

					Thread th = new Thread() {
						@Override
						public void run() {
							for (int i = 150; i >= 45; i--) {
								try {
									Thread.sleep(2);
								} catch (InterruptedException ex) {

								}
								jPanelMenu.setSize(i, jPanelMenu.getSize().height);
								lblMenu.setLocation(i - 37, 10);
							}
							// System.out.println(lblMenu.getLocation());

						}

					};
					th.start();

					sideBarOpen = false;

					// System.out.println("DONE");
				}
			}
		});
		
		JPanel panel = new JPanel();
		
		panel_1 = new JPanel();
		
		label_1 = new JLabel("");
		label_1.setIcon(new ImageIcon(MainForm.class.getResource("/swing/images/icons8_send_email_20px.png")));
		label_1.setToolTipText("Menu");
		label_1.setHorizontalAlignment(SwingConstants.CENTER);
		
		lblRecievedMails = new JLabel();
		lblRecievedMails.setText("Recieved Mails");
		lblRecievedMails.setHorizontalAlignment(SwingConstants.CENTER);
		lblRecievedMails.setFont(new Font("Tahoma", Font.PLAIN, 15));
		GroupLayout gl_panel_1 = new GroupLayout(panel_1);
		gl_panel_1.setHorizontalGroup(
			gl_panel_1.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_1.createSequentialGroup()
					.addContainerGap()
					.addComponent(label_1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblRecievedMails, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		gl_panel_1.setVerticalGroup(
			gl_panel_1.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_1.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_panel_1.createParallelGroup(Alignment.LEADING)
						.addComponent(label_1)
						.addComponent(lblRecievedMails, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		panel_1.setLayout(gl_panel_1);
		
		panel_2 = new JPanel();
		
		label_2 = new JLabel("");
		label_2.setIcon(new ImageIcon(MainForm.class.getResource("/swing/images/icons8_refresh_20px.png")));
		label_2.setToolTipText("Menu");
		label_2.setHorizontalAlignment(SwingConstants.CENTER);
		
		lblRefresh = new JLabel();
		lblRefresh.setText("Refresh");
		lblRefresh.setHorizontalAlignment(SwingConstants.CENTER);
		lblRefresh.setFont(new Font("Tahoma", Font.PLAIN, 15));
		GroupLayout gl_panel_2 = new GroupLayout(panel_2);
		gl_panel_2.setHorizontalGroup(
			gl_panel_2.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_2.createSequentialGroup()
					.addContainerGap()
					.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblRefresh, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		gl_panel_2.setVerticalGroup(
			gl_panel_2.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_2.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_panel_2.createParallelGroup(Alignment.LEADING)
						.addComponent(label_2, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblRefresh, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		panel_2.setLayout(gl_panel_2);
		
		panel_3 = new JPanel();
		
		label_3 = new JLabel("");
		label_3.setIcon(new ImageIcon(MainForm.class.getResource("/swing/images/icons8_customer_20px.png")));
		label_3.setToolTipText("Menu");
		label_3.setHorizontalAlignment(SwingConstants.CENTER);
		
		lblProfile = new JLabel();
		lblProfile.setText("Profile");
		lblProfile.setHorizontalAlignment(SwingConstants.CENTER);
		lblProfile.setFont(new Font("Tahoma", Font.PLAIN, 15));
		GroupLayout gl_panel_3 = new GroupLayout(panel_3);
		gl_panel_3.setHorizontalGroup(
			gl_panel_3.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_3.createSequentialGroup()
					.addContainerGap()
					.addComponent(label_3, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblProfile, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		gl_panel_3.setVerticalGroup(
			gl_panel_3.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel_3.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_panel_3.createParallelGroup(Alignment.LEADING)
						.addComponent(label_3)
						.addComponent(lblProfile, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		panel_3.setLayout(gl_panel_3);
		GroupLayout gl_jPanelMenu = new GroupLayout(jPanelMenu);
		gl_jPanelMenu.setHorizontalGroup(
			gl_jPanelMenu.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, gl_jPanelMenu.createSequentialGroup()
					.addGap(6)
					.addComponent(lblMenu)
					.addContainerGap(109, Short.MAX_VALUE))
				.addGroup(gl_jPanelMenu.createSequentialGroup()
					.addComponent(panel_3, GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
					.addContainerGap())
				.addGroup(gl_jPanelMenu.createSequentialGroup()
					.addGroup(gl_jPanelMenu.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(panel_2, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
						.addComponent(panel_1, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
						.addComponent(panel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
					.addContainerGap(18, Short.MAX_VALUE))
		);
		gl_jPanelMenu.setVerticalGroup(
			gl_jPanelMenu.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanelMenu.createSequentialGroup()
					.addGap(10)
					.addComponent(lblMenu)
					.addGap(18)
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(panel_2, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(panel_3, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(197, Short.MAX_VALUE))
		);
		
		label = new JLabel("");
		label.setIcon(new ImageIcon(MainForm.class.getResource("/swing/images/icons8_new_message_20px.png")));
		label.setToolTipText("Menu");
		label.setHorizontalAlignment(SwingConstants.CENTER);
		
		lblNewMail = new JLabel();
		lblNewMail.setFont(new Font("Tahoma", Font.PLAIN, 15));
		lblNewMail.setHorizontalAlignment(SwingConstants.CENTER);
		lblNewMail.setText("New Mail");
		GroupLayout gl_panel = new GroupLayout(panel);
		gl_panel.setHorizontalGroup(
			gl_panel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel.createSequentialGroup()
					.addContainerGap()
					.addComponent(label, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(lblNewMail, GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
		);
		gl_panel.setVerticalGroup(
			gl_panel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_panel.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
						.addComponent(label)
						.addComponent(lblNewMail, GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
					.addContainerGap())
		);
		panel.setLayout(gl_panel);
		jPanelMenu.setLayout(gl_jPanelMenu);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void mailMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mailMenuActionPerformed

	}// GEN-LAST:event_mailMenuActionPerformed

	private void newMailItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newMailItemActionPerformed
		HTMLEditorPane editor = new HTMLEditorPane();
		JFrame frame = new JFrame();
		JMenuBar menuBar = new JMenuBar();
		menuBar.add(editor.getEditMenu());
		menuBar.add(editor.getFormatMenu());
		menuBar.add(editor.getInsertMenu());
		frame.setJMenuBar(menuBar);

		frame.setTitle("New Mail");
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(800, 600);
		frame.getContentPane().add(editor);
		frame.setVisible(true);
	}// GEN-LAST:event_newMailItemActionPerformed

	private ArrayList<String[]> mailListDetails;
	private SQLiteConnector connection;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel detailsPanel;
	private javax.swing.JTextField fromInput;
	private javax.swing.JLabel fromLabel;
	private javax.swing.JMenu mailMenu;
	private javax.swing.JEditorPane mailText;
	private javax.swing.JScrollPane mailTextPane;
	private javax.swing.JMenuBar mainMenuBar;
	private javax.swing.JButton newMailBtn;
	private javax.swing.JMenuItem newMailItem;
	private javax.swing.JToggleButton speechBtn;
	private javax.swing.JPanel speechPanel;
	private javax.swing.JTextField subjectInput;
	private javax.swing.JLabel subjectLabel;
	private javax.swing.JTextField toInput;
	private javax.swing.JLabel toLabel;
	private JList mailList;
	private JLabel label;
	private JLabel label_1;
	private JLabel label_2;
	private JLabel label_3;
	private JPanel panel_1;
	private JPanel panel_2;
	private JPanel panel_3;
	private JLabel lblNewMail;
	private JLabel lblRecievedMails;
	private JLabel lblRefresh;
	private JLabel lblProfile;
}
