/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailzy;

import java.util.regex.Pattern;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;

import net.atlanticbb.tantlinger.shef.HTMLEditorPane;
import javax.swing.JPanel;


import java.awt.Color;

import javax.mail.MessagingException;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.Image;

import javax.swing.SwingConstants;
import java.awt.*;
import java.awt.Dimension;
import javax.swing.LayoutStyle.ComponentPlacement;



import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Toolkit;

/**
 *
 * @author lalexandrov
 */
public class NewMailDialog extends javax.swing.JDialog {
    /**
     * Creates new form NewMailDialog
     */
    public NewMailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
		
        List<Image> icons = new ArrayList<Image>();
		icons.add(Toolkit.getDefaultToolkit().getImage(MainForm.class.getResource("/swing/images/22x22.png")));
		icons.add(Toolkit.getDefaultToolkit().getImage(MainForm.class.getResource("/swing/images/32x32.png")));
		
		setIconImages(icons);
        addWindowListener(new WindowAdapter() {
        	@Override
        	public void windowClosing(WindowEvent e) {
        		resetDiaogData();
        	}
        });
        initComponents();
        

        menuBar.add(editor.getEditMenu());
        menuBar.add(editor.getFormatMenu());
        menuBar.add(editor.getInsertMenu());
        button.setEnabled(true);
        this.getContentPane().setLayout(null);
        labelTo.setText("To");
        labelSubject.setText("Subject");
		labelTo.setBounds(10,25,50,20);
		labelSubject.setBounds(10,45,50,20);
		textTo.setBounds(70,25,300,20);
		textSubject.setBounds(70,45,300,20);
		
		this.getContentPane().add(labelTo);
		this.getContentPane().add(labelSubject);
		this.getContentPane().add(textTo);
		this.getContentPane().add(textSubject);
		
		
        button.setBounds(680,665,100,40);
        this.getContentPane().add(button);
        editor.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		isValidBody();
        	}
        });
        editor.setBounds(0, 80, 780, 600);
        this.getContentPane().add(editor);
        this.setVisible(true);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	labelTo = new javax.swing.JLabel();
    	labelSubject = new javax.swing.JLabel();
    	
    	textTo = new javax.swing.JTextField();
    	textTo.addFocusListener(new FocusAdapter() {
    		@Override
    		public void focusLost(FocusEvent e) {
    			//showNotification();
    			isValidEmail();
    			isValidTo();
    		}
    	});
    	textSubject = new javax.swing.JTextField();
    	textSubject.addFocusListener(new FocusAdapter() {
    		@Override
    		public void focusLost(FocusEvent e) {
    			isValidSubject();
    		}
    	});
    	textSubject.addKeyListener(new KeyAdapter() {
    		@Override
    		public void keyPressed(KeyEvent e) {
    			subjectLen();
    		}
    	});
    	
        button = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setTitle("New Mail");
        setName("New Mail"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 770));
        setResizable(false);

        button.setText("Send");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	boolean isValid = isValidToSend();
            	if(isValid) {
                try {
					buttonActionPerformed(evt);
				} catch (MessagingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            	}
            	else {
            		System.out.println("Error");
            	}
                
            }
        });
        setJMenuBar(menuBar);
        
        panel = new JPanel();
        panel.setBackground(new Color(29, 44, 99));
        
        label = new JLabel();
        
        label_1 = new JLabel();
        label_1.setText("Mailzy");
        label_1.setPreferredSize(new Dimension(150, 50));
        label_1.setName("LOGO");
        label_1.setMinimumSize(new Dimension(150, 50));
        label_1.setMaximumSize(new Dimension(150, 50));
        label_1.setHorizontalAlignment(SwingConstants.CENTER);
        label_1.setForeground(Color.WHITE);
        label_1.setFont(new Font("Dialog", Font.BOLD, 36));
        label_1.setBackground(Color.WHITE);
        GroupLayout gl_panel = new GroupLayout(panel);
        gl_panel.setHorizontalGroup(
        	gl_panel.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 400, Short.MAX_VALUE)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(label)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(label_1, GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        			.addContainerGap())
        );
        gl_panel.setVerticalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 124, Short.MAX_VALUE)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addComponent(label, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        				.addComponent(label_1, GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
        			.addContainerGap())
        );
        panel.setLayout(gl_panel);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(428)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(panel, GroupLayout.PREFERRED_SIZE, 352, GroupLayout.PREFERRED_SIZE)
        				.addComponent(button))
        			.addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
        			.addGap(587)
        			.addComponent(button)
        			.addGap(47))
        );
        getContentPane().setLayout(layout);

        button.getAccessibleContext().setAccessibleName("button");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) throws MessagingException {//GEN-FIRST:event_buttonActionPerformed
        //TODO: Check if all fields are valid
    	//showNotification();
    	//hideNotification();
        this.setVisible(false);
        
    }//GEN-LAST:event_buttonActionPerformed
    
    
    private void isValidEmail() {
    	//List emails = new ArrayList();
    	String toEmail = textTo.getText();
    	String[] arr  = toEmail.split(" "); //Email to multiple addresses
    	String regex = "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])";
    	String notValid = "Invalid ";
    	boolean bol = false;
    	Pattern p = Pattern.compile(regex);
    	for(String test : arr) {
    		Matcher m = p.matcher(test);
    		System.out.println(test + " : " + m.matches());
    		if(m.matches()==false) {
    			
    			notValid +=" " +  test;
    			
    			bol=true;
    		}
    		
    	}
    	if(bol==true) {
    	labelTo.setToolTipText(notValid);
    	labelTo.setForeground(Color.red);
    	}
    	else
		{
			labelTo.setForeground(Color.black);
			labelTo.setToolTipText(null);
		}

    }
    
    private void subjectLen() {
    	if(textSubject.getText().length()>=40)
        {
			textSubject.setText(textSubject.getText().substring(0, 39));
        }
    }
    
    private boolean isValidTo() {
    	boolean isOk;
    	Color red = labelTo.getForeground();
    	if(red != Color.red) {
    		button.setEnabled(true);
    		isOk=true;
    	}
    	else {
    		isOk=false;
    		button.setEnabled(false);
    	}
    	return isOk;
    }
    
    private void isValidSubject() {
    	if(textSubject.getText().isBlank()) {
    		textSubject.setText("No subject");
    		button.setToolTipText("No subject");
    	}
    }
    private boolean isValidBody() {
    	boolean isOk;
    	if(editor.getText().isBlank()) {
    		JOptionPane.showMessageDialog(this, "Email is empty!");
    		isOk=false;
    	}
    	else {
    		isOk=true;
    	}
    	return isOk;
	}
    private boolean isValidToSend() {
    	boolean isValid;
    	boolean to=isValidTo();
    	boolean body=isValidBody();
    	if(to == true && body == true) {
    		isValid=true;
    	}
    	else {
    		isValid=false;
    	}
    	return isValid;
    }
    
//    private void showNotification() {
//    	labelNotification.setText("Send");
//    	Thread th = new Thread() {
//			@Override
//			public void run() {
//				for (int i = 0; i <= 150; i++) {
//					try {
//						Thread.sleep(8);
//					} catch (InterruptedException ex) {
//
//					}
//					panelNotification.setSize(panelNotification.getSize().width, i);
//					labelNotification.setLocation(i - 37, 10);
//				}
//				
//				// System.out.println(lblMenu.getLocation());
//			}
//
//		};
//		th.start();
//		
//    }
    public Mail getMail() {
    	if(this.textTo.getText().length() == 0 || this.textSubject.getText().length() == 0 || this.editor.getText() == "nAn")
    		return null;
    	return new Mail( this.textTo.getText(), this.textSubject.getText(), this.editor.getText() );
    }

	private void resetDiaogData() {
		this.editor.setText("nAn");
		this.textTo.setText("");
		this.textSubject.setText("");
	}

    
    private HTMLEditorPane editor = new HTMLEditorPane();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel labelTo;
    private javax.swing.JLabel labelSubject;
    private javax.swing.JTextField textTo;
    private javax.swing.JTextField textSubject;
    private JPanel panel;
    private JLabel label;
    private JLabel label_1;
}
